public class Vd {
    //instance variables
    short firstYear;
    boolean transferee;
    boolean returnee;
    String lastName;
    String firstName;
    String middleName;
    String address;
    int date;
    String birthPlace;
    String citizenship;
    String civilStatus;
    String sex;
    int contactNumber;
    String religion;
    String spouseName;
    int spouseContact;
    String fatherName;
    String motherName;
    String fatherWork;
    String motherWork;
    int fatherNumber;
    int motherNumber;
    String guardianName;
    int guardianNumber;
    String guardianAddress;
    String schoolName;
    int schoolStand;
    String lastSchool;
    int graduatedYear;
    short average;
    String course;
    int lastYear;
    String alsLearning;
    int yearTaken;
    String familyPs;
    int idNumber;
    String disability;
    String disabilityType;

    public static void main(String[] args) {
        //local variables
        short firstYear = 1;
        boolean transferee = false;
        boolean returnee = true;
        String lastName = "Ganti";
        String firstName = "Lakshmi";
        String middleName = "Harika";
        String address = "Vizag";
        int date = 23012004;
        String birthPlace = "Srikakulam";
        String citizenship = "Indian";
        String civilStatus = "Single";
        String sex = "Female";
        int contactNumber = 987654321;
        String religion = "Hindu";
        String spouseName = "No";
        int spouseContact = 789764356;
        String fatherName = "Ramu";
        String motherName = "Uma";
        String fatherWork = "Photography";
        String motherWork = "Teacher";
        int fatherNumber = 123456789;
        int motherNumber = 987654321;
        String guardianName = "Uncle";
        int guardianNumber = 112233445;
        String guardianAddress = "Hyderabad";
        String schoolName = "Narayana";
        int schoolStand = 10;
        String lastSchool = "Narayana";
        int graduatedYear = 2021;
        short average = 85;
        String course = "Computer Science";
        int lastYear = 2025;
        String alsLearning = "No";
        int yearTaken = 2023;
        String familyPs = "Yes";
        int idNumber = 1001;
        String disability = "No";
        String disabilityType = "No";

        System.out.println("First Year: " + firstYear);
        System.out.println("Transferee: " + transferee);
        System.out.println("Returnee: " + returnee);
        System.out.println("Last Name: " + lastName);
        System.out.println("First Name: " + firstName);
        System.out.println("Middle Name: " + middleName);
        System.out.println("Address: " + address);
        System.out.println("Date: " + date);
        System.out.println("Birthplace: " + birthPlace);
        System.out.println("Citizenship: " + citizenship);
        System.out.println("Civil Status: " + civilStatus);
        System.out.println("Sex: " + sex);
        System.out.println("Contact Number: " + contactNumber);
        System.out.println("Religion: " + religion);
        System.out.println("Spouse Name: " + spouseName);
        System.out.println("Spouse Contact: " + spouseContact);
        System.out.println("Father Name: " + fatherName);
        System.out.println("Mother Name: " + motherName);
        System.out.println("Father Work: " + fatherWork);
        System.out.println("Mother Work: " + motherWork);
        System.out.println("Father Number: " + fatherNumber);
        System.out.println("Mother Number: " + motherNumber);
        System.out.println("Guardian Name: " + guardianName);
        System.out.println("Guardian Number: " + guardianNumber);
        System.out.println("Guardian Address: " + guardianAddress);
        System.out.println("School Name: " + schoolName);
        System.out.println("School Stand: " + schoolStand);
        System.out.println("Last School: " + lastSchool);
        System.out.println("Graduated Year: " + graduatedYear);
        System.out.println("Average: " + average);
        System.out.println("Course: " + course);
        System.out.println("Last Year: " + lastYear);
        System.out.println("ALS Learning: " + alsLearning);
        System.out.println("Year Taken: " + yearTaken);
        System.out.println("Family PS: " + familyPs);
        System.out.println("ID Number: " + idNumber);
        System.out.println("Disability: " + disability);
        System.out.println("Disability Type: " + disabilityType);
    }
}
